modLoader="javafml"
loaderVersion="${loader_version_range}"

license="ARR"
[[mods]]
modId="season_innovation"
version="1.0.0"
displayName="Season Innovation"
authors="y271727uy"


description='''${mod_description}'''


[[dependencies.season_innovation]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.season_innovation]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.season_innovation]]
    modId="sereneseasons"
    mandatory=true
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.season_innovation]]
    modId="jade"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="CLIENT"


